#!/bin/bash

set -a
. ./.env
set +a

envsubst '${DATA_DIR} ${APP_NAME} ${BACKUP_DEST_TYPE} ${RCLONE_REMOTE} ${LOCAL_DEST_DIR} ${COMPRESSION_TYPE} ${ENCRYPT_BACKUP} ${ENCRYPTION_TYPE} ${AGE_PUBLIC_KEY} ${HEALTHCHECKS_URL} ${REMOTE_RETENTION_ENABLED} ${RETENTION_DAYS} ${EXCLUDE_PATTERNS} ${LOCK_DIR} ${ZSTD_FLAGS} ${LOCK_ENABLED}' < backup.sh.tmpl > backup.sh

envsubst '${RCLONE_NAME} ${RCLONE_TYPE} ${RCLONE_PROVIDER} ${RCLONE_ACCESS_KEY_ID} ${RCLONE_SECRET_ACCESS_KEY} ${RCLONE_ENDPOINT} ${RCLONE_NO_CHECK_BUCKET}' < rclone.conf.tmpl > rclone.conf

chmod 771 backup.sh
