---
- name: Rebuild initramfs
  ansible.builtin.command:
    cmd: mkinitfs

- name: Apply low-resource sysctl
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.d/99-low-resource.conf
  failed_when: false

- name: Apply swap sysctl
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.d/98-swap.conf

- name: Restart zram
  ansible.builtin.service:
    name: zram-init
    state: restarted
