# copy to .env for one application directory

# app backup
BACKUP_MODE=app
HOST_ROOT=./empty-host
APP_SOURCE_DIR=/srv/example-app
BACKUP_NAME=example-app

# snapshot host name. keep this stable.
RESTIC_HOST=example-host

# compose command on this host
COMPOSE_CMD=nerdctl compose

# notifications
# HEALTHCHECKS_URL=
NTFY_URL=https://ntfy.sh
# NTFY_TOPIC=
# NTFY_TOKEN_FILE=./secrets/ntfy_token.txt

# rest server auth. uncomment for a rest-server repository.
# REST_USERNAME_FILE=./secrets/rest_username.txt
# REST_PASSWORD_FILE=./secrets/rest_password.txt
# RESTIC_REST_USERNAME=
# RESTIC_REST_PASSWORD=

# tls for a private rest server
# RESTIC_CACERT=/certs/truenas-ca.crt
# RESTIC_TLS_CLIENT_CERT=
# RESTIC_INSECURE_TLS=

# restic tuning
# RESTIC_KEY_HINT=
RESTIC_COMPRESSION=auto
RESTIC_PACK_SIZE=64
# RESTIC_READ_CONCURRENCY=
# RESTIC_PROGRESS_FPS=
# RESTIC_NO_CACHE=

# alternate repository and password methods. files are the normal setup.
# RESTIC_REPOSITORY=
# RESTIC_REPOSITORY_FILE=
# RESTIC_PASSWORD_FILE=
# RESTIC_PASSWORD=
# RESTIC_PASSWORD_COMMAND=

# s3 and compatible storage
# AWS_SHARED_CREDENTIALS_FILE=/run/secrets/aws_credentials
# AWS_PROFILE=
# AWS_DEFAULT_REGION=
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# AWS_SESSION_TOKEN=
# RESTIC_AWS_ASSUME_ROLE_ARN=
# RESTIC_AWS_ASSUME_ROLE_SESSION_NAME=
# RESTIC_AWS_ASSUME_ROLE_EXTERNAL_ID=
# RESTIC_AWS_ASSUME_ROLE_POLICY=
# RESTIC_AWS_ASSUME_ROLE_REGION=
# RESTIC_AWS_ASSUME_ROLE_STS_ENDPOINT=

# restic copy source repository
# RESTIC_FROM_REPOSITORY=
# RESTIC_FROM_REPOSITORY_FILE=
# RESTIC_FROM_PASSWORD=
# RESTIC_FROM_PASSWORD_FILE=
# RESTIC_FROM_PASSWORD_COMMAND=
# RESTIC_FROM_KEY_HINT=

# azure
# AZURE_ACCOUNT_NAME=
# AZURE_ACCOUNT_KEY=
# AZURE_ACCOUNT_SAS=
# AZURE_ENDPOINT_SUFFIX=
# AZURE_FORCE_CLI_CREDENTIAL=

# backblaze b2
# B2_ACCOUNT_ID=
# B2_ACCOUNT_KEY=

# google cloud storage
# GOOGLE_PROJECT_ID=
# GOOGLE_APPLICATION_CREDENTIALS=
# GOOGLE_ACCESS_TOKEN=

# openstack swift
# OS_AUTH_URL=
# OS_REGION_NAME=
# OS_USERNAME=
# OS_USER_ID=
# OS_PASSWORD=
# OS_TENANT_ID=
# OS_TENANT_NAME=
# OS_USER_DOMAIN_NAME=
# OS_USER_DOMAIN_ID=
# OS_PROJECT_NAME=
# OS_PROJECT_DOMAIN_NAME=
# OS_PROJECT_DOMAIN_ID=
# OS_TRUST_ID=
# OS_APPLICATION_CREDENTIAL_ID=
# OS_APPLICATION_CREDENTIAL_NAME=
# OS_APPLICATION_CREDENTIAL_SECRET=
# OS_STORAGE_URL=
# OS_AUTH_TOKEN=
# ST_AUTH=
# ST_USER=
# ST_KEY=

# rclone backend
# RCLONE_BWLIMIT=
