---
- name: Apply debian foundation configuration
  hosts: debian_hosts
  become: true
  roles:
    - base

- name: Configure NUT Servers
  hosts: nut_servers
  become: true
  roles:
    - nut_server

- name: Configure NUT Clients
  hosts: nut_clients
  become: true
  roles:
    - nut_client
