---
all:
  children:
    # Generic groups, define physical attributes here once
    pve_nodes:
      hosts:
        pve-01:
          ansible_host: ${INTERNAL_NETWORK_PREFIX}10.4
        pve-02:
          ansible_host: ${INTERNAL_NETWORK_PREFIX}10.5
          mac_address: "AA:BB:CC:DD:EE:02"
        pve-03:
          ansible_host: ${INTERNAL_NETWORK_PREFIX}10.6
          mac_address: "AA:BB:CC:DD:EE:03"

    sbc_nodes::
      hosts:
        sbc-01:
          ansible_host: ${INTERNAL_NETWORK_PREFIX}10.20
    
    # Group hosts logically for specific playbooks
    # lab power zone
    power_zone_lab:
      children:
        pz_lab_servers:
          hosts:
            pve-01:
        pz_lab_clients:
          hosts:
            pve-03:

    # core power zone 
    power_zone_core:
      children:
        pz_core_servers:
          hosts:
        pz_core_clients:
          hosts:
