all:
  children:
    rpis:
      hosts:
        rpi-01:
          ansible_host: ${INTERNAL_NETWORK_PREFIX}30.3
    proxmox:
      hosts:
        pve-01:
          ansible_host: ${INTERNAL_NETWORK_PREFIX}10.4