all:
  children:
    rpis:
      hosts:
        rpi-01:
          ansible_host: 10.0.30.3
          ansible_user: dietpi
    proxmox:
      hosts:
        pve-01:
          ansible_host: 10.0.10.4
        pve-02:
          ansible_host: 10.0.