#!/usr/bin/env bash
# read secrets/password.txt, write bcrypt base64 into config/10-security.yaml

set -euo pipefail

TARGET_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${TARGET_DIR}"

if [ ! -f secrets/password.txt ]; then
  echo "missing secrets/password.txt - copy secrets/password.txt.example and edit"
  exit 1
fi

pass="$(tr -d '\r\n' < secrets/password.txt)"
if [ -z "${pass}" ]; then
  echo "password file is empty"
  exit 1
fi
if [ "${pass}" = "change-me-now" ]; then
  echo "password cannot be change-me-now"
  exit 1
fi

if [ -f .env ]; then
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi
user="${GATUS_AUTH_USER:-admin}"

echo "hashing password for user=${user}"
hash_b64="$(PASS="${pass}" python3 - <<'PY'
import base64, os, sys
try:
    import bcrypt
except ImportError:
    sys.stderr.write("python3-bcrypt missing - install with: pip install bcrypt\n")
    sys.stderr.write("or: apt install python3-bcrypt\n")
    sys.exit(1)
password = os.environ["PASS"].encode()
# cost 10 - gatus docs warn that high cost slows every request
hashed = bcrypt.hashpw(password, bcrypt.gensalt(rounds=10))
# normalize to $2a$ which some verifiers expect
if hashed.startswith(b"$2b$"):
    hashed = b"$2a$" + hashed[4:]
print(base64.b64encode(hashed).decode())
PY
)"

sec="config/10-security.yaml"
tmp="$(mktemp)"
cat > "${tmp}" <<EOF
# HTTP basic auth for the UI
# generated by scripts/hash-password.sh - do not edit the hash by hand
# plaintext is in secrets/password.txt (gitignored)

security:
  basic:
    username: "${user}"
    password-bcrypt-base64: "${hash_b64}"
EOF
mv "${tmp}" "${sec}"
echo "wrote ${sec}"
echo "restart gatus (or wait for config reload) for it to take effect"
