#!/bin/bash

set -eou pipefail

set -a
. ./.env
set +a

envsubst '${STANDARDNOTES_CONTAINER_NAME} ${STANDARDNOTES_HOST_PORT_0} ${STANDARDNOTES_HOST_PORT_1} ${STANDARDNOTES_NETWORK_NAME} ${LOCALSTACK_CONTAINER_NAME} ${DB_CONTAINER_NAME} ${DB_DATABASE} ${DB_USERNAME} ${DB_ROOT_PASSWD} ${DB_USER_PASSWD} ${REDIS_CONTAINER_NAME}' < compose.yml.tmpl > compose.yml

